name: test-workflow
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test application
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - run: echo y | $ANDROID_HOME/tools/bin/sdkmanager 'system-images;android-30;google_apis_playstore;x86_64'
      - run: echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-30;google_apis_playstore;x86_64'
      - run: $ANDROID_HOME/tools/android list avd
      - run: $ANDROID_HOME/tools/emulator64-arm -avd test -no-window -no-boot-anim -no-audio -verbose & wait-for-emulator

      - run: ls -al
      - run: echo "hello world"
