name: test-workflow
on: [push]
jobs:
  tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [25, 29, 30]
        target: [google_apis]
    steps:
    - name: some test
      run:  TEST1=blah; TEST2=bleh; echo $TEST1 $TEST2
      
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedCheck
      
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: app/build/outputs/androidTest-results/connected
